[package]
name = "recaptcha"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
my-telemetry = { tag = "1.3.0", git = "https://github.com/MyJetTools/my-telemetry.git" }
reqwest = { version = "*", features = ["json", "form"] }


serde = { version = "*", features = ["derive"] }
serde_json = "*"
